version: '3.9'

networks:
  velocity:
    driver: bridge

volumes:
  plugin_data:
  db_data:

services:
  proxy:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default
      - velocity
    environment:
      HEAP_SIZE: '1G'
    ports:
      - "25565:25577"
    volumes:
      - plugin_data:/plugin_data

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    env_file:
      - ./secrets/db.env
